var GPIO_CONFIG = map[string]string

GPIO_CONFIG["VALID_PIN"] = "0"
GPIO_CONFIG["INVALID_PIN"] = "16"
GPIO_CONFIG["VALID_DIGITAL_WRITE_VALUE"] = "HIGH"
GPIO_CONFIG["INVALID_DIGITAL_WRITE_VALUE"] = "MEDIUM"
GPIO_CONFIG["ANALOG_WRITE_VALUE"] = "100"
GPIO_CONFIG["ANALOG_READ_PIN"] = "A0"
GPIO_CONFIG["ANALOG_WRITE_PIN"] = "0"
GPIO_CONFIG["SUCCESS_RESPONSE"] = "1"
GPIO_CONFIG["FAILED_RESPONSE"] = "0"
GPIO_CONFIG["INVALID_PIN_RESPONSE"] = "Invalid pin value"
GPIO_CONFIG["INVALID_STATE_RESPONSE"] = "Invalid state"

var CREDENTIALS = map[string]string

CREDENTIALS["API_KEY"] = "xxxx"
CREDENTIALS["DEVICE_ID"] = "xxxx"
